version: '3.10'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_HOSTNAME: ${POSTGRES_HOST}
    ports:
      - "5432:5432"
    volumes:
      - "./postgres:/var/lib/postgresql/data"

  app:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: Neobis_Mobi_Market
    volumes:
      - .:/Neobis_Mobi_Market 
    ports:
      - "8000:8000"